// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Flow for suggesting improvements to a user's prompt based on feedback.
 *
 * - improvePrompt - The main function to improve the prompt.
 * - ImprovePromptInput - Input type for the improvePrompt function.
 * - ImprovePromptOutput - Output type for the improvePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImprovePromptInputSchema = z.object({
  originalPrompt: z.string().describe('The original prompt provided by the user.'),
  generatedResponse: z.string().describe('The AI-generated response to the original prompt.'),
  feedback: z.string().describe('The user feedback on the generated response.'),
});
export type ImprovePromptInput = z.infer<typeof ImprovePromptInputSchema>;

const ImprovePromptOutputSchema = z.object({
  improvedPrompt: z.string().describe('The improved prompt based on the feedback.'),
  explanation: z.string().describe('An explanation of why the prompt was improved.'),
});
export type ImprovePromptOutput = z.infer<typeof ImprovePromptOutputSchema>;

export async function improvePrompt(input: ImprovePromptInput): Promise<ImprovePromptOutput> {
  return improvePromptFlow(input);
}

const improvePromptPrompt = ai.definePrompt({
  name: 'improvePromptPrompt',
  input: {schema: ImprovePromptInputSchema},
  output: {schema: ImprovePromptOutputSchema},
  prompt: `You are an AI prompt improvement assistant. Given an original prompt, the AI's response, and user feedback, suggest an improved prompt and explain why the prompt was improved.

Original Prompt: {{{originalPrompt}}}
AI Response: {{{generatedResponse}}}
Feedback: {{{feedback}}}

Improved Prompt:`,
});

const improvePromptFlow = ai.defineFlow(
  {
    name: 'improvePromptFlow',
    inputSchema: ImprovePromptInputSchema,
    outputSchema: ImprovePromptOutputSchema,
  },
  async input => {
    const {output} = await improvePromptPrompt(input);
    return output!;
  }
);
